version: '3.8'

volumes:
  postgres_data:  # Для хранения данных PostgreSQL
  static_value:   # Для хранения статических файлов

services:
  # База данных
  db:
    image: postgres:12.4
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - django_network

  # Django-приложение
  web:
    build: .
    container_name: django_web
    environment:
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    restart: always
    volumes:
      - .:/code
      - ./static:/code/static
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - django_network

  # Nginx
  nginx:
    image: nginx:1.19.5
    container_name: nginx
    volumes:
      - ./static:/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django_network

networks:
  django_network:

